services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5434:5432"

  web:
    build: .
    # Let the entrypoint script manage the command parameters completely
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: